BaseArquitecturaArg/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basearq/', include("basearq.urls")),
    path('login/', auth_views.LoginView.as_view(template_name='basearq/debes_registrarte.html'), name='debes_registrarte')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basearq/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import views

urlpatterns = [


    path('home/', views.home, name="home"),
    path('contacto/', views.contacto, name='contacto'),
    path('buscar/', views.buscar, name='buscar'),


    path('recepcion_contacto/', views.recepcionContacto, name='recepcion_contacto'),

    path('twitter/', views.twitter, name='twitter'),
    path('facebook/', views.facebook, name='facebook'),

    
    path('pagina_en_construccion', views.facebook, name='pagina_en_construccion'),
    
    path('carga_usuarios/', views.registrate, name='carga_usuarios'),

    path('ingreso/', views.ingreso, name='ingreso'),
    path('editar_mi_perfil/', views.editarPerfil, name='editar_mi_perfil'),
    path('agregar_avatar/', views.agregarAvatar, name='agregar_avatar'),

    path('sobre_mi/', views.sobre_mi, name='sobre_mi'),
    
    path('salir/', LogoutView.as_view(template_name="basearq/salir.html"), name='salir'),

    path('agregar_usuario_admin/', views.crear_usuario_admin.as_view(), name='agregar_usuario_admin'),
    path('editar_usuario_admin/<int:pk>/', views.editar_usuario_admin.as_view(), name='editar_usuario_admin'),
    path('borrar_usuario_admin/<int:pk>/', views.borrar_usuario_admin.as_view(), name='borrar_usuario_admin'),
    path('ingreso/listado_usuarios_admin/', views.listado_usuarios_admin.as_view(template_name="basearq/listado_usuarios_admin.html"), name='listado_usuarios_admin'),

    path('listado_obras/', views.listado_obras, name='listado_obras'),
    path('listado_obras/agregar_obras/', views.cargar_obra, name='agregar_obras'),
    path('agregar_obras/', views.cargar_obra, name='agregar_obra_desde_home'),

    path('agregar_ciudad/', views.agregar_ciudad, name='agregar_ciudad'),
    path('agregar_arquitecto/', views.agregar_arquitecto, name='agregar_arquitecto'),
    
    path('listado_arquitectos/', views.listado_arquitectos, name='listado_arquitectos'),
    path('listado_ciudades/', views.listado_ciudades, name='listado_ciudades'),
    path('listado_nombre_obras/', views.listado_nombre_obras, name='listado_nombre_obras'),


    path('detalle_obras/<int:obra_id>/', views.detalle_obra, name='detalle_obra'),


    path('cambiar_contraseña/',auth_views.PasswordChangeView.as_view(template_name='basearq/cambiar_contraseña.html',success_url=reverse_lazy('editar_mi_perfil')),name='cambiar_contraseña'),



]

basearq/models.py
from django.db import models
from django.contrib.auth.models import User


#------------------CARGA DE OBRAS -----------------#


class Ciudad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Arquitecto(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Obra(models.Model):
    nombre = models.CharField(max_length=200)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    arquitectos = models.ManyToManyField(Arquitecto)
    fecha_publicacion = models.DateField(auto_now_add=True)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre

class ImagenObra(models.Model):
    obra = models.ForeignKey(Obra, on_delete=models.CASCADE, related_name='imagenes')
    imagen = models.ImageField(upload_to='obras/')  

    def __str__(self):
        return f"Imagen de {self.obra.nombre}"


#------------------CARGA DE AVATAR -----------------#

class Avatar(models.Model):
    imagen = models.ImageField(upload_to="avatares")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} {self.imagen}"

basearq/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import *


class RegistroForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput )
    password2 = forms.CharField(label="Confirma tu Contraseña", widget=forms.PasswordInput )
    admin_code = forms.CharField(label="Código de administrador (opcional)", required=False, max_length=50)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UsuarioEditForm(UserChangeForm):  
    email = forms.EmailField(required=True)
    first_name = forms.CharField(label="Nombre", max_length=20, required=True)
    last_name = forms.CharField(label="Apellido", max_length=20, required=True)

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            self.fields.pop('password')



#------------------AVATAR -----------------#

class AvatarForm(forms.Form):
    imagen = forms.ImageField(required=True)


#------------------CARGA DE OBRAS -----------------#

class ObraForm(forms.ModelForm):
    class Meta:
        model = Obra
        fields = ['nombre', 'ciudad', 'arquitectos', 'descripcion']

class ImagenObraForm(forms.ModelForm):
    class Meta:
        model = ImagenObra
        fields = ['imagen']

class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ['nombre']

class ArquitectoForm(forms.ModelForm):
    class Meta:
        model = Arquitecto
        fields = ['nombre']

basearq/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect

from django.urls import reverse_lazy

from django.http import HttpResponse

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from django.db.models import Q

from .models import *
from .forms import *



#-------------- PAGINA EN CONSTRUCCION--------------------#

def pagina_en_construccion(request):
    return render(request, "basearq/pagina_en_construccion.html")

#---------------- REDES SOCIALES-----------------------#

def twitter(request):
    return render(request, "basearq/pagina_en_construccion.html")

def facebook(request):
    return render(request, "basearq/pagina_en_construccion.html")

#--------------------ARQUITECTO--------------------#

def agregar_arquitecto(request):
    return render(request, "basearq/agregar_arquitecto.html")

#--------------------NAVBAR--------------------#

def home(request):
    return render(request, "basearq/home.html")


def buscar(request):
    query = request.GET.get('q', '')
    if query:
        obras = Obra.objects.filter(
            Q(nombre__icontains=query) |
            Q(ciudad__nombre__icontains=query) |
            Q(arquitectos__nombre__icontains=query)
        ).distinct()
    else:
        obras = Obra.objects.all()

    return render(request, "basearq/buscar.html", {'obras': obras,'query': query,})


def contacto(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        email = request.POST.get('email')
        asunto = request.POST.get('asunto')
        mensaje = request.POST.get('mensaje')

        print(f'Contacto de: {nombre} - {email} - Asunto: {asunto} - Mensaje: {mensaje}')

        return render(request, 'basearq/recepcion_contacto.html')

    return render(request, 'basearq/contacto.html') 

def recepcionContacto(request):
    return render(request, "basearq/recepcion_contacto.html")


def sobre_mi(request):
    return render(request, "basearq/sobre_mi.html")

#----------------CBV---CRUD DE ADMINISTRADOR---------------#

class listado_usuarios_admin(LoginRequiredMixin, ListView):
    model = User
    template_name = 'basearq/listado_usuarios_admin.html'  
    context_object_name = 'usuarios'

class crear_usuario_admin(LoginRequiredMixin, CreateView):
    model = User
    fields = ["first_name", "last_name", "email", "username" ]
    template_name = 'basearq/agregar_usuario_admin.html' 
    success_url = reverse_lazy("listado_usuarios_admin")

class editar_usuario_admin(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "email", "username", ]
    template_name = 'basearq/agregar_usuario_admin.html' 
    success_url = reverse_lazy("listado_usuarios_admin")

class borrar_usuario_admin(LoginRequiredMixin, DeleteView):
    model = User
    fields = ["first_name", "last_name", "email", "username" ]
    template_name = 'basearq/borrar_usuario_admin.html' 
    success_url = reverse_lazy("listado_usuarios_admin")


#----------------EDITAR PERFIL USUARIO---------------#

@login_required
def editarPerfil(request):
    usuario = request.user

    if request.method == "POST":
        miform = UsuarioEditForm(request.POST, instance=usuario)
        avatar_form = AvatarForm(request.POST, request.FILES)

        if miform.is_valid() and avatar_form.is_valid():
            
            miform.save()

            
            imagen = avatar_form.cleaned_data.get("imagen")
            if imagen:
                
                Avatar.objects.filter(user=usuario).delete()
                nuevo_avatar = Avatar(user=usuario, imagen=imagen)
                nuevo_avatar.save()

                
                request.session["avatar"] = nuevo_avatar.imagen.url

            return redirect(reverse_lazy('home'))
    else:
        miform = UsuarioEditForm(instance=usuario)
        avatar_form = AvatarForm()

    return render(request, 'basearq/editar_mi_perfil.html', {'form': miform, 'avatar_form': avatar_form})


#----------------Registrate / Ingresa----------------------------#

def registrate(request):
    if request.method == "POST":
        miformulario = RegistroForm(request.POST)
        if miformulario.is_valid():
            user = miformulario.save(commit=False)
            
            admin_code = miformulario.cleaned_data.get('admin_code')
            if admin_code == 'SOYADMIN2025':  
                user.is_staff = True
                user.is_superuser = True
                
            user.save()
            return redirect(reverse_lazy('home'))
    else:
        miformulario = RegistroForm()

    return render(request, 'basearq/carga_usuarios.html', {"form": miformulario})


def ingreso(request):
    if request.method == "POST":
        usuario = request.POST["username"]
        clave = request.POST["password"]
        user = authenticate(request, username=usuario, password=clave)

        if user is not None:
            login(request, user)

            
            if user.is_superuser:
                return redirect('listado_usuarios_admin')  
            else:
                return redirect('home') 

        else:
            return redirect(reverse_lazy('ingreso'))
    else:
        miform = AuthenticationForm()

    return render(request, "basearq/ingreso.html", {"form": miform})


#----------------AVATAR----------------------------#

@login_required
def agregarAvatar(request):
    if request.method == "POST":
        miform = AvatarForm(request.POST, request.FILES)
        if miform.is_valid():
            usuario = request.user
            imagen = miform.cleaned_data["imagen"]
            
            avatarviejo = Avatar.objects.filter(user=usuario)
            avatarviejo.delete()  
            
            avatar = Avatar(user=usuario, imagen=imagen)
            avatar.save()

            request.session["avatar"] = avatar.imagen.url

            return redirect(reverse_lazy("home"))
    else:
        miform = AvatarForm()
    
    return render(request, "basearq/editar_mi_perfil.html", {"form": miform})


#----------------NUEVAS OBRAS--------------------------#

@login_required
def cargar_obra(request):
    if request.method == 'POST':
        obra_form = ObraForm(request.POST)
        imagen_form = ImagenObraForm(request.POST, request.FILES)

        if obra_form.is_valid() and imagen_form.is_valid():
            obra = obra_form.save()
            imagen = imagen_form.cleaned_data['imagen']
            ImagenObra.objects.create(obra=obra, imagen=imagen)
            return redirect('listado_obras')  
    else:
        obra_form = ObraForm()
        imagen_form = ImagenObraForm()

    return render(request, 'basearq/agregar_obras.html', {'obra_form': obra_form,'imagen_form': imagen_form})


@login_required
def agregar_ciudad(request):
    if request.method == 'POST':
        form = CiudadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agregar_obras')  
    else:
        form = CiudadForm()
    return render(request, 'basearq/agregar_ciudad.html', {'form': form})


@login_required
def agregar_arquitecto(request):
    if request.method == 'POST':
        form = ArquitectoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('agregar_obras')  
    else:
        form = ArquitectoForm()
    return render(request, 'basearq/agregar_arquitecto.html', {'form': form})


#----------------LISTADO DE OBRAS CON BUSCADOR--------------------------#

@login_required
def listado_obras(request):
    query = request.GET.get('q', '')
    
    if query:
        obras = Obra.objects.filter(Q(nombre__icontains=query) | Q(ciudad__nombre__icontains=query) | Q(arquitectos__nombre__icontains=query)).distinct()
    else:
        obras = Obra.objects.all()
    
    return render(request, 'basearq/listado_obras.html', {'obras': obras,'query': query})


#----------------BUSCAR DE ARQUITECTOS / OBRAS / CIUDADES--------------------------#


def listado_arquitectos(request):
    arquitectos = Arquitecto.objects.all()
    return render(request, 'basearq/listado_arquitectos.html', {'arquitectos': arquitectos}) 

def listado_ciudades(request):
    ciudades = Ciudad.objects.all()
    return render(request, 'basearq/listado_ciudades.html', {'ciudades': ciudades}) 

def listado_nombre_obras(request):
    obras = Obra.objects.all()
    return render(request, 'basearq/listado_nombre_obras.html', {'obras': obras})

#----------------DETALLE DE LAS OBRAS--------------------------#

def detalle_obra(request, obra_id):
    obra = get_object_or_404(Obra, pk=obra_id)
    return render(request, 'basearq/detalle_obra.html', {'obra': obra})

basearq/templates/basearq/agregar_ciudad.html
{% extends "basearq/index.html" %}
{% load static %}


{% block imagendefondo %}
        
<header class="masthead" style="background-image: url('{% static 'assets/img/cargaciudad.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">

{% endblock imagendefondo %}

{% block titulo %}

<h1>Agregar Ciudad</h1>
<span class="subheading">Las obras iconicas de la arquitectura Argentina</span>

{% endblock titulo %}


{% block contenido %}

<div class="container mt-5">
    <h4>Agregar Ciudad</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Guardar</button>
        <a href="{% url 'agregar_obras' %}" class="btn btn-secondary">Volver</a>
    </form>
</div>



{% endblock contenido %}

basearq/templates/basearq/agregar_obras.html
{% extends "basearq/index.html" %}
{% load static %}


{% block imagendefondo %}
        
<header class="masthead" style="background-image: url('{% static 'assets/img/agregarobra.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">

{% endblock imagendefondo %}

{% block titulo %}

<h1>Agregar Obra</h1>
<span class="subheading">Las obras iconicas de la arquitectura Argentina</span>

{% endblock titulo %}


{% block contenido %}

        <div class="mb-4 d-flex justify-content-end gap-2">
    <a href="{% url 'agregar_ciudad' %}" class="btn btn-outline-primary btn-sm">
        <i class="fas fa-plus-circle"></i> Nueva Ciudad
    </a>
    <a href="{% url 'agregar_arquitecto' %}" class="btn btn-outline-primary btn-sm">
        <i class="fas fa-plus-circle"></i> Nuevo Arquitecto
    </a>
</div>


        <form method="post" enctype="multipart/form-data" class="container mt-5">
    {% csrf_token %}
    <div class="card p-4 shadow">
        <h4 class="mb-4 text-center">Cargar nueva obra</h4>

        <!-- Formulario de obra -->
        {% for field in obra_form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="text-danger small">{{ field.errors|striptags }}</div>
                {% endif %}
            </div>
        {% endfor %}

        <!-- Imagen -->
        <div class="mb-3">
            <label class="form-label">{{ imagen_form.imagen.label }}</label>
            {{ imagen_form.imagen }}
            {% if imagen_form.imagen.errors %}
                <div class="text-danger small">{{ imagen_form.imagen.errors|striptags }}</div>
            {% endif %}
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-upload"></i> Cargar Obra
            </button>
        </div>
    </div>
</form>



{% endblock contenido %}

basearq/templates/basearq/borrar_usuario_admin.html
{% extends "basearq/index.html" %}
{% load static %}

{% block imagendefondo %}
        
<header class="masthead" style="background-image: url('{% static 'assets/img/perfiladmin.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">

{% endblock imagendefondo %}

{% block titulo %}

<h1>Borrar Usuario</h1>
<span class="subheading">Solo para administradores</span>

{% endblock titulo %}


{% block contenido %}

<div class="container mt-5">
    <div class="card">
        <div class="card-body text-center">
            <h4>¿Estás seguro de que querés borrar al usuario <strong>{{ object.username }}</strong>?</h4>
            <form method="post">
                {% csrf_token %}
                <div class="mt-4">
                    <button type="submit" class="btn btn-danger">Sí, borrar</button>
                    <a href="{% url 'listado_usuarios_admin' %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

basearq/templates/basearq/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> ArqArgentina </title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- Font Awesome  -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-RXf+QSDCUQs6Bv6MM2pcbtC5a2wO+e5wWg6pU5qDZ1ycXnWr33I9SXDcZ6+5HqYj1T6nX3a6ZKw5tUoGXf6Zqw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body style="background-color: #f5f5f5;">

        <!-- Navigation-->
        
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#">{% now "d/m/Y" %}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'buscar' %}">Buscar</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contacto' %}">Contacto</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sobre_mi' %}">Sobre mí</a></li>
                </ul>

                <!--BOTONES Y AUTENTICACION-->
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}

                        <!-- Botón administrador -->
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a href="{% url 'listado_usuarios_admin' %}"
                            class="btn px-lg-3 py-3 py-lg-2"
                            style="background-color: #ffc107; color: black; margin-left: 10px; margin-top: 8px;">
                                <i class="fas fa-users-cog"></i> Admin Usuarios
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'pagina_en_construccion' %}"
                            class="btn px-lg-3 py-3 py-lg-2"
                            style="background-color: #ffc107; color: black; margin-left: 10px; margin-top: 8px;">
                                <i class="fas fa-building"></i> Admin Obras
                            </a>
                        </li>

                        {% endif %}

                        <!-- Botón Salir -->
                        <li class="nav-item">
                            <form method="post" action="{% url 'salir' %}" style="margin: 0;">
                                {% csrf_token %}
                                <button type="submit"
                                        class="btn btn-danger px-lg-3 py-3 py-lg-2"
                                        style="margin-top: 8px;">
                                    <i class="fas fa-sign-out-alt"></i> Salir
                                </button>
                            </form>
                        </li>

                        <!-- Botón Mi Perfil -->

                        <li class="nav-item">
                            <a href="{% url 'editar_mi_perfil' %}"
                            class="btn px-lg-3 py-3 py-lg-2"
                            style="background-color: #e9ecef; color: black; margin-left: 10px; margin-top: 8px;">
                                <i class="fas fa-id-badge"></i> Mi Perfil
                            </a>
                        </li>

                        <!-- Avatar - Nombre de usuario -->

                        <li class="nav-item d-flex align-items-center px-lg-3 py-3 py-lg-2"
                            style="background-color: #e9ecef; border-radius: 5px; margin-left: 10px; margin-top: 8px;">
                            
                            {% with request.session.avatar as avatar_session %}
                                {% if avatar_session %}
                                    <img src="{{ avatar_session }}" alt="avatar"
                                        class="rounded-circle me-2"
                                        style="width: 30px; height: 30px; object-fit: cover;">
                                {% else %}
                                    {% with user.avatar_set.last as avatar %}
                                        {% if avatar %}
                                            <img src="{{ avatar.imagen.url }}" alt="avatar"
                                                class="rounded-circle me-2"
                                                style="width: 30px; height: 30px; object-fit: cover;">
                                        {% else %}
                                            <i class="fas fa-user-circle fa-lg me-2" style="color: black;"></i>
                                        {% endif %}
                                    {% endwith %}
                                {% endif %}
                            {% endwith %}

                            <span style="color: black;">{{ user.username }}</span>
                        </li>
                    {% else %}

                        <!-- Ingreso y Registro -->

                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'ingreso' %}">
                                <i class="fas fa-sign-in-alt"></i> Ingresa
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'carga_usuarios' %}">
                                <i class="fas fa-user-plus"></i> Regístrate
                            </a>
                        </li>
                    {% endif %}
                </ul>



            </div>
        </div>
    </nav>


        <!-- BLOQUE IMAGEN DE FONDO-->
        {% block imagendefondo %}
        
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static '' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">

        {% endblock imagendefondo %}


                            <!-- BLOQUE DE TITULO-->
                            {% block titulo %}
                            
                            <h1>¿Quien soy?</h1>
                            <span class="subheading">Acá les cuento...</span>

                            {% endblock titulo %}
                            <!-- FIN BLOQUE DE TITULO-->

                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- BLOQUE DE CONTENIDO-->

        {% block contenido %}
        


        {% endblock contenido %}

        <!-- FIN BLOQUE DE CONTENIDO-->

        <!-- Footer-->

<footer class="border-top mt-7">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item mx-2">
                        <a href="{% url 'twitter' %}">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item mx-2">
                        <a href="{% url 'facebook' %}">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Agora Contenidos &copy; Junio 2025</div>
            </div>
        </div>
    </div>
</footer>

    </body>
</html>

basearq/templates/basearq/pagina_en_construccion.html
{% extends "basearq/index.html" %}
{% load static %}

{% block imagendefondo %}
        
<header class="masthead" style="background-image: url('{% static 'assets/img/PaginaEnConstruccion.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">

{% endblock imagendefondo %}

{% block titulo %}

<h1>En breve estara disponible</h1>
<span class="subheading">Disculpa las molestias, te invitamos a seguir recorriendo esta pagina</span>

{% endblock titulo %}


{% block contenido %}





{% endblock contenido %}